### PR TITLE
added api interface for compatibility with ffi capable languages

### PR DESCRIPTION
**Pull request by EddieMataEwy**
Please check compilation, as I had to use my own compilation with Visual Studio instead of using make/cmake to create the working DLL. Only tested on Windows but it should export the API on Linux as well. Not sure about MacOS compilation.

### CODE REVIEW

**Comment by EddieMataEwy** [comment]
Sorry, I have to fix something.

**Comment by bupticybee** [comment]
Running CI

**Comment by bupticybee** [comment]
Can you provide a description in readme format as well?

**Comment by EddieMataEwy** [comment]
Sure, I'll create a new resources directory with a brief explanation and examples in different languages.
Does that sound good?

**Pull request merged**
