### PR TITLE
Add Github Action (current failing in test step)

### PR DESCRIPTION
**Pull request by Endle**

### CODE REVIEW

**Comment by bupticybee** [comment]
I will look in to the error in ci, thanks for the contribution~

**Comment by Endle** [comment]
BTW @bupticybee do you interest in using the build matrix in windows, mac and Linux?  I had a try but failed when setting up the build env. If so, I can spend a bit more time on it

**Comment by bupticybee** [comment]
> BTW @bupticybee do you interest in using the build matrix in windows, mac and Linux? I had a try but failed when setting up the build env. If so, I can spend a bit more time on it

I checked the error,  I already have an idea what's could be wrong in the ci process.

BTW, I believe the correct gramma is " are you interest in ...." not "do you interest in ..." haha

Anyway, In normal ci process I remember there is already a way to run things (build, release,etc) in parallel. I take a few look in the build matrix document, it didn't mention anything about multiplatform compile stuff, I mean in order to do that at least you should specific docker image or something like that, but Is there a image for Windows or Mac? I'm not sure.

**Comment by Endle** [comment]
> 
> BTW, I believe the correct gramma is " are you interest in ...." not "do you interest in ..." haha
> 

Nice catch :)

> Anyway, In normal ci process I remember there is already a way to run things (build, release,etc) in parallel. I take a few look in the build matrix document, it didn't mention anything about multiplatform compile stuff, I mean in order to do that at least you should specific docker image or something like that, but Is there a image for Windows or Mac? I'm not sure.

Well, it's easy to set up multi-platform with GIthub Action. Just change it to
```
os: [ubuntu-latest, macos-latest]
```
or adding windows platform as well. I'm done it in several personal projects, [e.g.](https://github.com/Endle/rust-bundler-cp/blob/176f9f22cdbdcaa874c0ee0943dfe5ac810fa868/.github/workflows/rust.yml#L20)

This page lists the virtual environments provided by GIthub Action: https://github.com/actions/virtual-environments

**Comment by bupticybee** [comment]
> https://github.com/actions/virtual-environments

Seems quite nice,I definitely am going to look into this.

**Comment by bupticybee** [comment]
> > BTW, I believe the correct gramma is " are you interest in ...." not "do you interest in ..." haha
> 
> Nice catch :)
> 
> > Anyway, In normal ci process I remember there is already a way to run things (build, release,etc) in parallel. I take a few look in the build matrix document, it didn't mention anything about multiplatform compile stuff, I mean in order to do that at least you should specific docker image or something like that, but Is there a image for Windows or Mac? I'm not sure.
> 
> Well, it's easy to set up multi-platform with GIthub Action. Just change it to
> 
> ```
> os: [ubuntu-latest, macos-latest]
> ```
> 
> or adding windows platform as well. I'm done it in several personal projects, [e.g.](https://github.com/Endle/rust-bundler-cp/blob/176f9f22cdbdcaa874c0ee0943dfe5ac810fa868/.github/workflows/rust.yml#L20)
> 
> This page lists the virtual environments provided by GIthub Action: https://github.com/actions/virtual-environments

Seems quite nice,I definitely am going to look into this.

**Comment by bupticybee** [comment]
Already done merging, and ci is all correct in master now

**Pull request merged**
