### PR TITLE
compress table file

### PR DESCRIPTION
**Pull request by yffbit**
The strength of 5 cards is determined by suit distribution and rank distribution. For the offsuit combination, we only need rank distribution. So we need two hash tables. One for suited combination, use cards mask as key. One for offsuit combination, use rank distribution mask as key. In this way, number of records reduced from 2598960 to 5148+6175=11323, from 376992 to 504+1278=1782, respectively.

### CODE REVIEW

**Comment by bupticybee** [comment]
This is very interesting, I will spend some time veryfying it and do some tests. 
Did you do some benchmarking? How does this change affect the speed of the solver and accuracy?

**Comment by bupticybee** [comment]
If I underestand this correctly, this change mainly affects the loading speed,right? So it does not change the solving speed and accuracy?

**Comment by yffbit** [comment]
> 

Yes. It speed up the loading process and save some memory. It doesn't change the cfr process.

**Comment by bupticybee** [comment]
> Yes. It speeds up the loading process and saves some memory. It doesn't change the cfr process.

Okay I see. I will do some test first. Thanks very much for your effort.

**Comment by yffbit** [comment]
> Hi, I read the code, is it possible to make the new bin file normal txt file? I think it would not hurt the performance much, and would be much easier for any other developer to reuse in other languages.

To generate normal text file, just change the implementation of save() and load() function as you want.

**Comment by bupticybee** [comment]
> > Hi, I read the code, is it possible to make the new bin file normal txt file? I think it would not hurt the performance much, and would be much easier for any other developer to reuse in other languages.
> 
> To generate normal text file, just change the implementation of save() and load() function as you want.

Aha, I see that.

**Comment by bupticybee** [comment]
Merged to gui brach, after tests are complete will merge this to master.

**Comment by bupticybee** [comment]
UPDATE:  I have done some slight modification to the code and now it works prefectly on mac.
It did speed up the loading process a lot.  
Will transfer the code to linux branch after some futher checks. Thanks for the effort!

**Pull request merged**
