### PR TITLE
beta coefficient in discounted CFR

### PR DESCRIPTION
**Pull request by mvuthegoat**
Should we change beta to beta_coef here? 
I read the paper on Discounted CFR (https://cdn.aaai.org/ojs/4007/4007-13-7066-1-10-20190704.pdf?_gl=1*le8l1f*_ga*Mzc2NzU4NDM0LjE2ODE3NjcxMDM.*_ga_CKNBPFEYPG*MTY4MTc2NzEwMi4xLjAuMTY4MTc2NzExMS4wLjAuMA..), and it says multiply negative regrets by the beta coefficient instead of just beta as shown in the code.
I might be missing something, though.

### CODE REVIEW

**Comment by bupticybee** [comment]
> Should we change beta to beta_coef here? I read the paper on Discounted CFR (https://cdn.aaai.org/ojs/4007/4007-13-7066-1-10-20190704.pdf?_gl=1*le8l1f*_ga*Mzc2NzU4NDM0LjE2ODE3NjcxMDM.*_ga_CKNBPFEYPG*MTY4MTc2NzEwMi4xLjAuMTY4MTc2NzExMS4wLjAuMA..), and it says multiply negative regrets by the beta coefficient instead of just beta as shown in the code. I might be missing something, though.

I think you found a implementation bug here. Wonder how the result would change after fixing it.

**Comment by bupticybee** [comment]
I review the paper and the code, in the paper they refer to  "α = 3/2, β = 0, and γ = 2 " as a optimal parameter.
In their formular
截屏2023-04-28 13 48 21

beta_coef equals 1 / (1+ 1) , which would always be 1/2. So I replace coef_beta with a constant 1/2 in my implementation.

**Comment by bupticybee** [comment]
I run your code, and compair it with baseline, and it's performance is worse than baseline. I will delay the merge until the performance problem is solved.

ps: always create pull request to gui branch, which most change happens.

**Comment by mvuthegoat** [comment]
Oh, I see you use beta as 1/2 directly, which is indeed 1 / (1 + 1). You can keep the code the same, though:)

**Pull request closed without merging**
